
export enum Filters {
    EVERY = 'every',
    LIGHT_RESISTENCE_INSULINE = 'lightResistenceInsuline',
    MEDIUM_RESISTENCE_INSULINE = 'mediumResistenceInsuline',
    SEVERE_RESISTENCE_INSULINE = 'severeResistenceInsuline',
    DIABETES = 'diabetes',
    LIGHT_AMPUTATION_RISK = 'lightAmputationRisk',
    MEDIUM_AMPUTATION_RISK = 'mediumAmputationRisk',
    SEVERE_AMPUTATION_RISK = 'severeAmputationRisk',
    SEVERE_METABOLIC_SICKNESS = 'severeMetabolicSickness',
    LIGHT_HYPERTENSION = 'lightHypetension',
    MEDIUM_HYPERTENSION = 'mediumHypetension',
    SEVERE_HYPERTENSION = 'severeHypetension',
    HYPERTENSION_PEAK_RISK = 'hypertensionPeakRisk',
    HEART_ATTACK_STROKE_RISK = 'heartAttackStrokeRisk',
    SERIOUS_CARDIO_EVENT_RISK = 'seriousCardioEventRisk',
    OVERWEIGHT = 'overweight',
    OBESETY_LEVEL_ONE = 'obesety1',
    OBESETY_LEVEL_TWO = 'obesety2',
    OBESETY_LEVEL_THREE = 'obesety3',
    ELEVATED_STRESS = 'elevatedStress',
    SEVERE_STRESS = 'severeStress',
    VAGAL_SYNDROME = 'vagalSyndrome',
    ADHD = 'adhd',
    LIGHT_MEDIUM_DEPRESSION = 'lightOrMediumDepression',
    SEVERE_DEPRESSION = 'severeDepression'
}